---
title: "await/catch を使うときの early return"
emoji: "🤔"
type: "idea"
topics:
  - "javascript"
  - "ポエム"
published: true
published_at: "2020-10-14 18:48"
---

*この記事は ポエム です*

try/catchで書くとcatchの中で簡単にearly returnできますよね

```js
(async () => {
  try {
    await new Promise((_, reject) => {
      reject('something went wrong!')
    })
  } catch(err) {
    console.log('caught!', err)
    return
  }
  console.log('ok~~')
})()

// caught! something went wrong!
```

こんな感じ

個人的にtry/catchの見た目が好きじゃないのでなるべく使いたくないってのもありますが、
Promiseにcatch生えてるのにtryする？って思うんですよね

でも単純に書き換えるだけだと

``` js
(async () => {
  const ret = await new Promise((_, reject) => {
    reject('something went wrong!')
  }).catch((err) => {
    console.log('caught!', err)
    return
  })
  console.log('ok~~')
})()

// caught! something went wrong!
// ok~~
```

「ok~~ ☆〜（ゝ。∂）」じゃあないんだよ

でも

``` js
(async () => {
  let success = true
  await new Promise((_, reject) => {
    reject('something went wrong!')
  }).catch((err) => {
    console.log('caught!', err)
    success = false
  })
  if(!success) {
    return
  }
  console.log('ok~~')
})()

// caught! something went wrong!
```

これじゃダサいですよね

だから最善手は、
戻り値のない処理でもなんとか`resolve('_')`とかやって、
`Promise<void>`としないように自分ルールを作った上で、

``` js
(async () => {
  const ret = await new Promise((_, reject) => {
    // これはresolveすることないですが…
    reject('something went wrong!')
  }).catch((err) => {
    console.log('caught!', err)
  })
  if(!ret) {
    return
  }
  console.log('ok~~')
})()

// caught! something went wrong!
```
	
とすることかなって思うんです


でも実態が`Promise<void>`なのにこれのためにstring返したりするの、
あんまりホメられたことじゃないと思うんですよね

みなさんどうしてるんですか？
やっぱりtry/catchですか？